version: '3.8'

services:
  # MongoDB 데이터베이스
  mongodb:
    image: mongo:latest
    container_name: nestjs-mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: nestjs_2fa
    volumes:
      - mongodb_data:/data/db
    networks:
      - nestjs-network

  # NestJS 애플리케이션
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_2fa
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/nestjs_2fa?authSource=admin
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - nestjs-network

  # MongoDB 관리 도구
  mongo-express:
    image: mongo-express:1.0.2
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - nestjs-network

volumes:
  mongodb_data:

networks:
  nestjs-network:
    driver: bridge